"""add raspberrypi table and pi_id to board

Revision ID: 2a2bbb3190d2
Revises: 7879c47297a5
Create Date: 2026-04-19 13:07:35.241169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2a2bbb3190d2'
down_revision: Union[str, Sequence[str], None] = '7879c47297a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raspberrypi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host')
    )
    with op.batch_alter_table('board') as batch_op:
        batch_op.add_column(sa.Column('pi_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_board_pi_id', 'raspberrypi', ['pi_id'], ['id'])
        batch_op.drop_column('pi_host')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board') as batch_op:
        batch_op.add_column(sa.Column('pi_host', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint('fk_board_pi_id', type_='foreignkey')
        batch_op.drop_column('pi_id')
    op.drop_table('raspberrypi')
    # ### end Alembic commands ###
