"""add unique constraints to ports and config_file

Revision ID: 5985b8e22561
Revises: 
Create Date: 2026-04-14 16:14:26.016924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5985b8e22561'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('serial_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_file', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gdb_port', sa.Integer(), nullable=False),
    sa.Column('telnet_port', sa.Integer(), nullable=False),
    sa.Column('tcl_port', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pi_host', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('openocd_pid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_file'),
    sa.UniqueConstraint('gdb_port'),
    sa.UniqueConstraint('serial_number'),
    sa.UniqueConstraint('tcl_port'),
    sa.UniqueConstraint('telnet_port')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board')
    # ### end Alembic commands ###
