"""unified_json_session

Revision ID: e28832216e1e
Revises: 50e3fa7c6b2c
Create Date: 2026-04-25 18:47:58.192946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e28832216e1e'
down_revision: Union[str, Sequence[str], None] = '50e3fa7c6b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('json_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_board_sn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('control_board_sn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['control_board_sn'], ['board.serial_number'], ),
    sa.ForeignKeyConstraint(['target_board_sn'], ['board.serial_number'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('raspberrypi')
    op.drop_table('device_session')
    op.drop_table('application_session')
    op.add_column('board', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint(op.f('fk_board_pi_id'), 'board', type_='foreignkey')
    op.drop_column('board', 'id')
    op.drop_column('board', 'pi_id')
    op.drop_column('board', 'telnet_port')
    op.drop_column('board', 'config_file')
    op.drop_column('board', 'name')
    op.drop_column('board', 'gdb_port')
    op.drop_column('board', 'tcl_port')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('tcl_port', sa.INTEGER(), nullable=False))
    op.add_column('board', sa.Column('gdb_port', sa.INTEGER(), nullable=False))
    op.add_column('board', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.add_column('board', sa.Column('config_file', sa.VARCHAR(), nullable=True))
    op.add_column('board', sa.Column('telnet_port', sa.INTEGER(), nullable=False))
    op.add_column('board', sa.Column('pi_id', sa.INTEGER(), nullable=False))
    op.add_column('board', sa.Column('id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(op.f('fk_board_pi_id'), 'board', 'raspberrypi', ['pi_id'], ['id'])
    op.drop_column('board', 'type')
    op.create_table('application_session',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('target_board_id', sa.INTEGER(), nullable=False),
    sa.Column('control_board_id', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.DATETIME(), nullable=False),
    sa.Column('end_time', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['control_board_id'], ['board.id'], ),
    sa.ForeignKeyConstraint(['target_board_id'], ['board.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_application_session_user')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_session',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('board_id', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.DATETIME(), nullable=False),
    sa.Column('end_time', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_device_session_user')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raspberrypi',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('host', sa.VARCHAR(), nullable=False),
    sa.Column('user', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host')
    )
    op.drop_table('session')
    # ### end Alembic commands ###
